version: "3.9"
services:
  api:
    build: .
    ports: ["4000:4000"]
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_NAME=payment
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_DIALECT=postgres
    volumes:
      - ./uploads:/app/uploads
    depends_on: [db]

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: payment
    ports: ["5432:5432"]
